services:
  fastapi:
    image: 786923080007.dkr.ecr.sa-east-1.amazonaws.com/churn-fastapi:latest
    # image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/churn-fastapi:latest
    # Replace <ACCOUNT_ID> and <AWS_REGION> with your actual AWS account ID and region
    ports:
      - "8000:8000"
    environment:
      AWS_REGION: "sa-east-1"
      # AWS_REGION: "<AWS_REGION>"
      # Replace <AWS_REGION> with your actual AWS region
      PROD_S3_URI: "s3://churn-production/champion-model/"
      MONITORING_LOG_S3_URI: "s3://churn-production/monitoring_logs/"
    networks:
      - monitoring
    restart: unless-stopped # Ensure the container restarts automatically

  streamlit_app:
    image: 786923080007.dkr.ecr.sa-east-1.amazonaws.com/churn-streamlit:latest
    # image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/churn-streamlit:latest
    # Replace <ACCOUNT_ID> and <AWS_REGION> with your actual AWS account ID and region
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    environment:
      FASTAPI_API_URL: "http://fastapi:8000"
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.8.0
    ports:
      - "9090:9090"
    volumes:
      - /opt/churn/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/churn/monitoring/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.3
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
