artifacts_root: artifacts

data_ingestion:
  db_host: "localhost"
  db_user: "root"
  db_password: "12345"
  db_name: "bank_db"
  base_query: "SELECT {} FROM churners;"
  root_dir: artifacts/data_ingestion
  feature_store_file_path: artifacts/data_ingestion/feature_store/ingested_data.csv
  training_file_path: artifacts/data_ingestion/ingested/train.csv
  testing_file_path: artifacts/data_ingestion/ingested/test.csv
  train_test_split_ratio: 0.2
  random_state: 42

data_validation:
  root_dir: artifacts/data_validation
  validation_report_path: artifacts/data_validation/status.json

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/feature_store/ingested_data.csv
