artifacts_root: artifacts

data_ingestion:
  db_host: "localhost"
  db_user: "pedro"
  db_password: "12345"
  db_name: "bank_db"
  query: "SELECT * FROM churners;"
  root_dir: artifacts/data_ingestion
  feature_store_file_path: artifacts/data_ingestion/feature_store/ingested_data.csv
  training_file_path: artifacts/data_ingestion/ingested/train.csv
  testing_file_path: artifacts/data_ingestion/ingested/test.csv
  train_test_split_ratio: 0.2

data_validation:
  root_dir: artifacts/data_validation
  drift_report_file_path: artifacts/data_validation/drift_report/report.html

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/feature_store/ingested_data.csv
