XGBClassifier:
  n_estimators: 468
  max_depth: 6
  learning_rate: 0.025
  subsample: 0.77
  colsample_bytree: 0.62
  random_state: 42

RandomForestClassifier:
  n_estimators: 391
  max_depth: 15
  min_samples_split: 4
  min_samples_leaf: 3
  max_features: "log2"
  random_state: 42
