columns:
  Attrition_Flag: object
  Total_Relationship_Count: int64 #*
  Credit_Limit: int64 #-
  Total_Revolving_Bal: int64 #-*
  Total_Amt_Chng_Q4_Q1: float64 #-
  Total_Trans_Amt: int64 #-*
  Total_Trans_Ct: int64 #*
  Total_Ct_Chng_Q4_Q1: float64 #*
  Avg_Utilization_Ratio: float64 #-

target_column:
  name: Attrition_Flag

drop_columns:
  Avg_Utilization_Ratio: float64
  Total_Amt_Chng_Q4_Q1: float64
  Credit_Limit: int64

selected_features:
  Total_Relationship_Count: int64
  Total_Revolving_Bal: int64
  Total_Trans_Amt: int64
  Total_Trans_Ct: int64
  Total_Ct_Chng_Q4_Q1: float64
  Activity_Growth: float64
  Customer_Value: float64
