global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "/etc/prometheus/alert_rules.yml"  # Load alerting rules from this file

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["fastapi:8000"]
      # This part must match the service name and port of the FastAPI app in docker-compose.yaml
      # Containers are reachable by their service names (Docker DNS) within the Docker network

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
